# Generated by Django 5.0.1 on 2024-01-19 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_renting.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
